### PR TITLE
Added maven support

### PR DESCRIPTION
**Pull request by mbenz89**
This commit includes a POM file for building, testing and deploying infoflow-android with Maven.
We use it to build and deploy infoflow-android on our Soot build server. If you are interested, we can share the needed Maven dependency, so that everyone can obtain our infoflow-android build via Maven.

### CODE REVIEW

**Comment by JulianSchuette** [comment]
Needs additional dependency for me to compile:
```
<dependency>
    <groupId>com.google.protobuf</groupId>
    <artifactId>protobuf-java</artifactId>
    <version>2.5.0</version>
</dependency>
```

**Comment by mbenz89** [comment]
Seems like Protobuf was added a few days ago. I'll add it.

Thanks for reporting!

**Comment by malindadoo** [comment]
Could you please share the mavan repository for soot-infoflow-android. I am going to use this as a dependency lib. Thanks.

**Comment by mbenz89** [comment]
Here you go:

```
    <dependencies>
       <dependency>
            <groupId>de.tud.sse</groupId>
            <artifactId>soot-infoflow-android</artifactId>
            <version>2.0.0-SNAPSHOT</version>
        </dependency>
    </dependencies>
    <repositories>
        <repository>
            <id>soot-snapshot</id>
            <name>soot snapshots</name>
            <url>https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-snapshot/</url>
        </repository>
    </repositories>
```

**Comment by malindadoo** [comment]
Thank you for the prompt response. It gives the following error..

`Downloading: https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-snapshot/de/tud/sse/soot-infoflow-android/2.0.0-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata de.tud.sse:soot-infoflow-android:2.0.0-SNAPSHOT/maven-metadata.xml from/to soot-snapshot (https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-snapshot/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[WARNING] Failure to transfer de.tud.sse:soot-infoflow-android:2.0.0-SNAPSHOT/maven-metadata.xml from https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-snapshot/ was cached in the local repository, resolution will not be reattempted until the update interval of soot-snapshot has elapsed or updates are forced. Original error: Could not transfer metadata de.tud.sse:soot-infoflow-android:2.0.0-SNAPSHOT/maven-metadata.xml from/to soot-snapshot (https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-snapshot/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
`
Could you please help me with this.

**Comment by mbenz89** [comment]
Our SSL certificate is generated by Let'sEncrypt. The certificate is not trusted by older java versions, so you basically have two options here:
1. Install the newest JDK
2. Install the certificate manually to your keystore. You might want to give this a try: https://gist.github.com/hedefalk/9442c224e7de4739e8cee6b7e88c4d7f

1.

**Comment by malindadoo** [comment]
I moved with the first option. It works. Thank you.

**Comment by malindadoo** [comment]
Hello,
Is 2.0.0-SNAPSHOT the latest version? In this version  SetupApplication.calculateSourcesSinksEntrypoints(Collections.emptySet(), Collections.emptySet()); is not available. I have used soot and soot-infoflow-android as dependencies.

**Comment by mbenz89** [comment]
Yes, this is the latest nightly build. 
The method you are trying to call was removed and is no longer supported, which is why you cannot find it.

What are you trying to do?
Most of the times you either want to call runInfoFlow or constructCallGraph.

**Pull request merged**
